app:
  name: "test"
  mode: "dev"
  port: 9091
  version: "v1"

log:
  level: "debug"
  filename: "TikTok.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "571400yst"
  db: "TikTok"
  max_open_connection: 20
  max_idle_connection: 10

redis:
  host: 127.0.0.1
  port: 16379
  password: ""
  db: 0
  pool_size: 100

encrypt:
  secret_key: "&12JsXXa@"

gin:
  mode: "debug"

snowflake:
  start_time: "2020-07-01"
  machine_id: 1

auth:
  jwt_expire: 8760